In [1]:
import pandas as pd

In [2]:
matches = pd.read_csv("matches.csv", index_col=0)

In [3]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2,0,West Ham,...,Match Report,NaN,13.0,1.0,18.7,1.0,1.0,1.0,2022,Manchester City
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4,0,Bournemouth,...,Match Report,NaN,19.0,7.0,17.5,0.0,0.0,0.0,2022,Manchester City
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3,3,Newcastle Utd,...,Match Report,NaN,21.0,10.0,16.2,1.0,0.0,0.0,2022,Manchester City
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4,2,Crystal Palace,...,Match Report,NaN,18.0,5.0,14.1,0.0,0.0,0.0,2022,Manchester City
5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6,0,Nott'ham Forest,...,Match Report,NaN,17.0,9.0,14.8,0.0,0.0,0.0,2022,Manchester City

In [4]:
matches.shape

(1520, 27)

In [5]:
# 2 seasons * 20 squads * 38 matches

2 * 20 * 38# 2 seasons * 20 squads * 38 matches

2 * 20 * 38

1520

In [6]:
# Missing Liverpool 2021-2022
matches["team"].value_counts()

Manchester City             76
Crystal Palace              76
Southampton                 76
Leeds United                76
Leicester City              76
Everton                     76
West Ham United             76
Wolverhampton Wanderers     76
Arsenal                     76
Chelsea                     76
Brentford                   76
Tottenham Hotspur           76
Aston Villa                 76
Brighton and Hove Albion    76
Liverpool                   76
Newcastle United            76
Manchester United           76
Fulham                      38
Bournemouth                 38
Nottingham Forest           38
Burnley                     38
Watford                     38
Norwich City                38
Name: team, dtype: int64

In [7]:
matches[matches["team"] == "Liverpool"].sort_values("date")

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,2021-08-14,17:30,Premier League,Matchweek 1,Sat,Away,W,3,0,Norwich City,...,Match Report,NaN,19.0,6.0,17.3,1.0,0.0,0.0,2021,Liverpool
1,2021-08-21,12:30,Premier League,Matchweek 2,Sat,Home,W,2,0,Burnley,...,Match Report,NaN,27.0,8.0,16.1,0.0,0.0,0.0,2021,Liverpool
2,2021-08-28,17:30,Premier League,Matchweek 3,Sat,Home,D,1,1,Chelsea,...,Match Report,NaN,23.0,6.0,16.2,0.0,1.0,1.0,2021,Liverpool
3,2021-09-12,16:30,Premier League,Matchweek 4,Sun,Away,W,3,0,Leeds United,...,Match Report,NaN,30.0,8.0,16.1,1.0,0.0,0.0,2021,Liverpool
5,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,W,3,0,Crystal Palace,...,Match Report,NaN,25.0,10.0,16.4,1.0,0.0,0.0,2021,Liverpool
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,2023-05-03,20:00,Premier League,Matchweek 28,Wed,Home,W,1,0,Fulham,...,Match Report,NaN,14.0,2.0,22.6,0.0,1.0,1.0,2022,Liverpool
48,2023-05-06,17:30,Premier League,Matchweek 35,Sat,Home,W,1,0,Brentford,...,Match Report,NaN,15.0,5.0,18.8,0.0,0.0,0.0,2022,Liverpool
49,2023-05-15,20:00,Premier League,Matchweek 36,Mon,Away,W,3,0,Leicester City,...,Match Report,NaN,16.0,5.0,17.5,1.0,0.0,0.0,2022,Liverpool
50,2023-05-20,15:00,Premier League,Matchweek 37,Sat,Home,D,1,1,Aston Villa,...,Match Report,NaN,10.0,5.0,18.2,0.0,0.0,0.0,2022,Liverpool
51,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Away,D,4,4,Southampton,...,Match Report,NaN,30.0,8.0,18.5,0.0,0.0,0.0,2022,Liverpool

In [8]:
matches["round"].value_counts()

Matchweek 1     40
Matchweek 30    40
Matchweek 23    40
Matchweek 12    40
Matchweek 24    40
Matchweek 25    40
Matchweek 26    40
Matchweek 27    40
Matchweek 29    40
Matchweek 31    40
Matchweek 2     40
Matchweek 33    40
Matchweek 34    40
Matchweek 28    40
Matchweek 35    40
Matchweek 36    40
Matchweek 37    40
Matchweek 32    40
Matchweek 22    40
Matchweek 21    40
Matchweek 7     40
Matchweek 20    40
Matchweek 3     40
Matchweek 4     40
Matchweek 5     40
Matchweek 6     40
Matchweek 8     40
Matchweek 9     40
Matchweek 10    40
Matchweek 11    40
Matchweek 13    40
Matchweek 14    40
Matchweek 15    40
Matchweek 16    40
Matchweek 17    40
Matchweek 18    40
Matchweek 19    40
Matchweek 38    40
Name: round, dtype: int64

In [9]:
matches.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf                int64
ga                int64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk              float64
pkatt           float64
season            int64
team             object
dtype: object

In [10]:
del matches["comp"]

In [11]:
del matches["notes"]

In [12]:
matches["date"] = pd.to_datetime(matches["date"])

In [13]:
matches["target"] = (matches["result"] == "W").astype("int")

In [14]:
matches

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,match report,sh,sot,dist,fk,pk,pkatt,season,team,target
1,2022-08-07,16:30,Matchweek 1,Sun,Away,W,2,0,West Ham,2.2,...,Match Report,13.0,1.0,18.7,1.0,1.0,1.0,2022,Manchester City,1
2,2022-08-13,15:00,Matchweek 2,Sat,Home,W,4,0,Bournemouth,1.7,...,Match Report,19.0,7.0,17.5,0.0,0.0,0.0,2022,Manchester City,1
3,2022-08-21,16:30,Matchweek 3,Sun,Away,D,3,3,Newcastle Utd,2.1,...,Match Report,21.0,10.0,16.2,1.0,0.0,0.0,2022,Manchester City,0
4,2022-08-27,15:00,Matchweek 4,Sat,Home,W,4,2,Crystal Palace,2.2,...,Match Report,18.0,5.0,14.1,0.0,0.0,0.0,2022,Manchester City,1
5,2022-08-31,19:30,Matchweek 5,Wed,Home,W,6,0,Nott'ham Forest,3.3,...,Match Report,17.0,9.0,14.8,0.0,0.0,0.0,2022,Manchester City,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2022-04-30,15:00,Matchweek 35,Sat,Away,L,0,2,Aston Villa,0.5,...,Match Report,9.0,3.0,21.6,0.0,0.0,0.0,2021,Norwich City,0
39,2022-05-08,14:00,Matchweek 36,Sun,Home,L,0,4,West Ham,0.8,...,Match Report,8.0,2.0,22.2,1.0,0.0,0.0,2021,Norwich City,0
40,2022-05-11,19:45,Matchweek 21,Wed,Away,L,0,3,Leicester City,1.1,...,Match Report,9.0,5.0,17.0,0.0,0.0,0.0,2021,Norwich City,0
41,2022-05-15,14:00,Matchweek 37,Sun,Away,D,1,1,Wolves,1.1,...,Match Report,11.0,2.0,14.4,0.0,0.0,0.0,2021,Norwich City,0
42,2022-05-22,16:00,Matchweek 38,Sun,Home,L,0,5,Tottenham,0.5,...,Match Report,9.0,0.0,18.6,0.0,0.0,0.0,2021,Norwich City,0

In [15]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes

In [16]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [17]:
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")

In [18]:
matches["day_code"] = matches["date"].dt.dayofweek

In [19]:
matches

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,fk,pk,pkatt,season,team,target,venue_code,opp_code,hour,day_code
1,2022-08-07,16:30,Matchweek 1,Sun,Away,W,2,0,West Ham,2.2,...,1.0,1.0,1.0,2022,Manchester City,1,0,21,16,6
2,2022-08-13,15:00,Matchweek 2,Sat,Home,W,4,0,Bournemouth,1.7,...,0.0,0.0,0.0,2022,Manchester City,1,1,2,15,5
3,2022-08-21,16:30,Matchweek 3,Sun,Away,D,3,3,Newcastle Utd,2.1,...,1.0,0.0,0.0,2022,Manchester City,0,0,15,16,6
4,2022-08-27,15:00,Matchweek 4,Sat,Home,W,4,2,Crystal Palace,2.2,...,0.0,0.0,0.0,2022,Manchester City,1,1,7,15,5
5,2022-08-31,19:30,Matchweek 5,Wed,Home,W,6,0,Nott'ham Forest,3.3,...,0.0,0.0,0.0,2022,Manchester City,1,1,17,19,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2022-04-30,15:00,Matchweek 35,Sat,Away,L,0,2,Aston Villa,0.5,...,0.0,0.0,0.0,2021,Norwich City,0,0,1,15,5
39,2022-05-08,14:00,Matchweek 36,Sun,Home,L,0,4,West Ham,0.8,...,1.0,0.0,0.0,2021,Norwich City,0,1,21,14,6
40,2022-05-11,19:45,Matchweek 21,Wed,Away,L,0,3,Leicester City,1.1,...,0.0,0.0,0.0,2021,Norwich City,0,0,11,19,2
41,2022-05-15,14:00,Matchweek 37,Sun,Away,D,1,1,Wolves,1.1,...,0.0,0.0,0.0,2021,Norwich City,0,0,22,14,6
42,2022-05-22,16:00,Matchweek 38,Sun,Home,L,0,5,Tottenham,0.5,...,0.0,0.0,0.0,2021,Norwich City,0,1,19,16,6

In [20]:
from sklearn.ensemble import RandomForestClassifier

In [21]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [22]:
train = matches[matches["date"] < '2022-01-01']

In [23]:
test = matches[matches["date"] > '2022-01-01']

In [24]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [25]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [26]:
train = matches[matches["date"] < '2022-01-01']

In [27]:
test = matches[matches["date"] > '2022-01-01']

In [28]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [29]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [30]:
preds = rf.predict(test[predictors])

In [31]:
from sklearn.metrics import accuracy_score

In [32]:
error = accuracy_score(test["target"], preds)

In [33]:
error

0.5958188153310104

In [34]:
combined = pd.DataFrame(dict(actual=test["target"], predicted=preds))

In [35]:
pd.crosstab(index=combined["actual"], columns=combined["predicted"])

predicted    0    1
actual
0          542  158
1          306  142

In [36]:
from sklearn.metrics import precision_score

precision_score(test["target"], preds)

0.47333333333333333

In [37]:
grouped_matches = matches.groupby("team")

In [38]:
group = grouped_matches.get_group("Manchester City").sort_values("date")

In [39]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [40]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

rolling_averages(group, cols, new_cols)

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
4,2021-09-11,15:00,Matchweek 4,Sat,Away,W,1,0,Leicester City,2.8,...,15,5,3.333333,0.333333,19.666667,6.000000,16.866667,0.666667,0.000000,0.000000
6,2021-09-18,15:00,Matchweek 5,Sat,Home,D,0,0,Southampton,1.0,...,15,5,3.666667,0.000000,22.000000,7.333333,15.866667,0.333333,0.000000,0.000000
8,2021-09-25,12:30,Matchweek 6,Sat,Away,W,1,0,Chelsea,1.7,...,12,5,2.000000,0.000000,22.000000,6.333333,15.166667,0.333333,0.000000,0.000000
10,2021-10-03,16:30,Matchweek 7,Sun,Away,D,2,2,Liverpool,1.2,...,16,6,0.666667,0.000000,18.666667,4.000000,15.933333,0.333333,0.000000,0.000000
11,2021-10-16,15:00,Matchweek 8,Sat,Home,W,2,0,Burnley,2.1,...,15,5,1.000000,0.666667,14.333333,2.333333,16.833333,0.666667,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,2023-05-06,15:00,Matchweek 35,Sat,Home,W,2,1,Leeds United,2.6,...,15,5,3.000000,0.666667,13.666667,8.000000,15.433333,0.000000,0.333333,0.333333
54,2023-05-14,14:00,Matchweek 36,Sun,Away,W,3,0,Everton,0.8,...,14,6,2.333333,0.666667,14.666667,7.000000,16.366667,0.666667,0.333333,0.666667
56,2023-05-21,16:00,Matchweek 37,Sun,Home,W,1,0,Chelsea,1.2,...,16,6,2.666667,0.333333,14.000000,5.666667,18.100000,1.333333,0.000000,0.333333
57,2023-05-24,20:00,Matchweek 32,Wed,Away,D,1,1,Brighton,1.8,...,20,2,2.000000,0.333333,13.666667,4.000000,18.933333,1.333333,0.000000,0.333333
58,2023-05-28,16:30,Matchweek 38,Sun,Away,L,0,1,Brentford,1.6,...,16,6,1.666667,0.333333,12.333333,3.333333,17.333333,0.666667,0.000000,0.000000

In [41]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [42]:
matches_rolling

                                 date   time         round  day venue result  \
team
Arsenal                 4  2021-09-11  15:00   Matchweek 4  Sat  Home      W
                        5  2021-09-18  15:00   Matchweek 5  Sat  Away      W
                        7  2021-09-26  16:30   Matchweek 6  Sun  Home      W
                        8  2021-10-02  17:30   Matchweek 7  Sat  Away      D
                        9  2021-10-18  20:00   Matchweek 8  Mon  Home      D
...                               ...    ...           ...  ...   ...    ...
Wolverhampton Wanderers 39 2023-04-29  15:00  Matchweek 34  Sat  Away      L
                        40 2023-05-06  15:00  Matchweek 35  Sat  Home      W
                        41 2023-05-13  15:00  Matchweek 36  Sat  Away      L
                        42 2023-05-20  15:00  Matchweek 37  Sat  Home      D
                        43 2023-05-28  16:30  Matchweek 38  Sun  Away      L

                            gf  ga        opponent   xg  ...  hour  day_code  \
team                                                     ...
Arsenal                 4    1   0    Norwich City  2.7  ...    15         5
                        5    1   0         Burnley  1.1  ...    15         5
                        7    3   1       Tottenham  1.1  ...    16         6
                        8    0   0        Brighton  0.4  ...    17         5
                        9    2   2  Crystal Palace  1.7  ...    20         0
...                         ..  ..             ...  ...  ...   ...       ...
Wolverhampton Wanderers 39   0   6        Brighton  0.8  ...    15         5
                        40   1   0     Aston Villa  0.8  ...    15         5
                        41   0   2  Manchester Utd  0.3  ...    15         5
                        42   1   1         Everton  1.6  ...    15         5
                        43   0   5         Arsenal  0.5  ...    16         6

                            gf_rolling ga_rolling sh_rolling sot_rolling  \
team
Arsenal                 4     0.000000   3.000000   9.666667    2.333333
                        5     0.333333   2.333333  12.333333    3.000000
                        7     0.666667   1.666667  14.666667    3.000000
                        8     1.666667   0.333333  18.333333    5.333333
                        9     1.333333   0.333333  11.000000    4.000000
...                                ...        ...        ...         ...
Wolverhampton Wanderers 39    1.666667   0.666667  11.666667    4.666667
                        40    1.000000   2.666667  11.333333    2.333333
                        41    1.000000   2.000000   8.000000    2.000000
                        42    0.333333   2.666667   7.000000    1.333333
                        43    0.666667   1.000000   8.000000    2.333333

                           dist_rolling  fk_rolling  pk_rolling  pkatt_rolling
team
Arsenal                 4     14.833333    0.333333    0.000000       0.000000
                        5     14.133333    0.333333    0.000000       0.000000
                        7     14.800000    0.666667    0.000000       0.000000
                        8     18.433333    0.666667    0.000000       0.000000
                        9     19.833333    0.666667    0.000000       0.000000
...                                 ...         ...         ...            ...
Wolverhampton Wanderers 39    18.700000    0.666667    0.333333       0.333333
                        40    18.800000    0.666667    0.333333       0.333333
                        41    17.766667    0.000000    0.333333       0.333333
                        42    15.600000    0.000000    0.000000       0.000000
                        43    15.333333    0.333333    0.000000       0.000000

[1451 rows x 38 columns]

In [43]:
matches_rolling = matches_rolling.droplevel('team')

In [44]:
matches_rolling

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
4,2021-09-11,15:00,Matchweek 4,Sat,Home,W,1,0,Norwich City,2.7,...,15,5,0.000000,3.000000,9.666667,2.333333,14.833333,0.333333,0.000000,0.000000
5,2021-09-18,15:00,Matchweek 5,Sat,Away,W,1,0,Burnley,1.1,...,15,5,0.333333,2.333333,12.333333,3.000000,14.133333,0.333333,0.000000,0.000000
7,2021-09-26,16:30,Matchweek 6,Sun,Home,W,3,1,Tottenham,1.1,...,16,6,0.666667,1.666667,14.666667,3.000000,14.800000,0.666667,0.000000,0.000000
8,2021-10-02,17:30,Matchweek 7,Sat,Away,D,0,0,Brighton,0.4,...,17,5,1.666667,0.333333,18.333333,5.333333,18.433333,0.666667,0.000000,0.000000
9,2021-10-18,20:00,Matchweek 8,Mon,Home,D,2,2,Crystal Palace,1.7,...,20,0,1.333333,0.333333,11.000000,4.000000,19.833333,0.666667,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39,2023-04-29,15:00,Matchweek 34,Sat,Away,L,0,6,Brighton,0.8,...,15,5,1.666667,0.666667,11.666667,4.666667,18.700000,0.666667,0.333333,0.333333
40,2023-05-06,15:00,Matchweek 35,Sat,Home,W,1,0,Aston Villa,0.8,...,15,5,1.000000,2.666667,11.333333,2.333333,18.800000,0.666667,0.333333,0.333333
41,2023-05-13,15:00,Matchweek 36,Sat,Away,L,0,2,Manchester Utd,0.3,...,15,5,1.000000,2.000000,8.000000,2.000000,17.766667,0.000000,0.333333,0.333333
42,2023-05-20,15:00,Matchweek 37,Sat,Home,D,1,1,Everton,1.6,...,15,5,0.333333,2.666667,7.000000,1.333333,15.600000,0.000000,0.000000,0.000000
43,2023-05-28,16:30,Matchweek 38,Sun,Away,L,0,5,Arsenal,0.5,...,16,6,0.666667,1.000000,8.000000,2.333333,15.333333,0.333333,0.000000,0.000000

In [45]:
matches_rolling.index = range(matches_rolling.shape[0])

In [46]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2022-01-01']
    test = data[data["date"] > '2022-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    error = precision_score(test["target"], preds)
    return combined, error

In [47]:
combined, error = make_predictions(matches_rolling, predictors + new_cols)

In [48]:
error

0.4978540772532189

In [49]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [50]:
combined.head(10)

    actual  predicted       date     team        opponent result
17       0          0 2022-01-23  Arsenal         Burnley      D
18       1          0 2022-02-10  Arsenal          Wolves      W
19       1          0 2022-02-19  Arsenal       Brentford      W
20       1          1 2022-02-24  Arsenal          Wolves      W
21       1          1 2022-03-06  Arsenal         Watford      W
22       1          1 2022-03-13  Arsenal  Leicester City      W
23       0          1 2022-03-16  Arsenal       Liverpool      L
24       1          0 2022-03-19  Arsenal     Aston Villa      W
25       0          0 2022-04-04  Arsenal  Crystal Palace      L
26       0          0 2022-04-09  Arsenal        Brighton      L

In [51]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"Brighton and Hove Albion": "Brighton", "Manchester United": "Manchester Utd", "Newcastle United": "Newcastle Utd", "Tottenham Hotspur": "Tottenham", "West Ham United": "West Ham", "Wolverhampton Wanderers": "Wolves"} 
mapping = MissingDict(**map_values)

In [52]:
combined["new_team"] = combined["team"].map(mapping)

In [53]:
merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])

In [54]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal,0,0,Burnley,Arsenal,D,Burnley
1,1,0,2022-02-10,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
2,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal,0,0,Brentford,Arsenal,L,Brentford
3,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
4,1,1,2022-03-06,Arsenal,Watford,W,Arsenal,0,0,Watford,Arsenal,L,Watford
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,0,0,2023-04-29,Wolverhampton Wanderers,Brighton,L,Wolves,1,1,Brighton and Hove Albion,Wolves,W,Brighton
1091,1,0,2023-05-06,Wolverhampton Wanderers,Aston Villa,W,Wolves,0,0,Aston Villa,Wolves,L,Aston Villa
1092,0,0,2023-05-13,Wolverhampton Wanderers,Manchester Utd,L,Wolves,1,0,Manchester United,Wolves,W,Manchester Utd
1093,0,0,2023-05-20,Wolverhampton Wanderers,Everton,D,Wolves,0,0,Everton,Wolves,D,Everton
1094,0,0,2023-05-28,Wolverhampton Wanderers,Arsenal,L,Wolves,1,0,Arsenal,Wolves,W,Arsenal

In [55]:
merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] ==0)]["actual_x"].value_counts()

1    99
0    90
Name: actual_x, dtype: int64